name: Build website

on: [push, pull_request]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-22.04
    env:
      CI: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: make install-python-requirements
      - name: Build website
        run: (cd scripts && bash Generate_Site_mkDocs.sh)
      - name: List generated files
        run: ls -lah generated/site/
