name: Build website

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Build website
    runs-on: ubuntu-24.04
    env:
      CI: true
    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python 3
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'

      - name: Install system dependencies for lxml
        run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt1-dev
      - name: Install Python dependencies
        run: make install-python-requirements
      - name: Build website
        run: (cd scripts && bash Generate_Site_mkDocs.sh)
      - name: List generated files
        run: ls -lah generated/site/
